"""生成 index.html（内嵌 JSON，离线可用）"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
with open(ROOT/"data"/"curve_data.json",encoding="utf-8") as f:cd=json.load(f)
m=cd["meta"]
S='*{box-sizing:border-box;margin:0;padding:0}body{font-family:"Microsoft YaHei","PingFang SC",sans-serif;background:#f5f6fa;color:#2c3e50;padding:20px}h1{font-size:22px}.sub{color:#7f8c8d;font-size:14px;margin:4px 0 20px}.l{display:flex;gap:20px;flex-wrap:wrap}.ca{flex:1 1 660px;min-width:320px}.pa{flex:0 0 300px;background:#fff;border-radius:10px;padding:18px;box-shadow:0 0 8px rgba(0,0,0,.08)}.pa h3{font-size:15px;margin-bottom:14px;border-left:4px solid #c0392b;padding-left:10px}.f{margin:12px 0}.f label{display:block;font-size:13px;margin-bottom:4px;color:#555}.f input{width:100%;padding:7px 10px;border:1px solid #ddd;border-radius:6px;font-size:14px}.f input:focus{border-color:#2980b9}.rg{display:flex;gap:8px;flex-wrap:wrap}.rg label{display:flex;gap:4px;font-size:13px;cursor:pointer;border:1px solid #ddd;border-radius:6px;padding:5px 10px}.rg label:has(input:checked){border-color:#c0392b;background:#fff5f5}.rb{background:#f0f3f7;border-radius:8px;padding:14px;margin-top:14px}.rr{display:flex;justify-content:space-between;padding:5px 0;font-size:14px}.rr .l{color:#555}.rr .v{font-weight:bold}.hl{color:#c0392b;font-size:18px}.bd{display:inline-block;padding:3px 10px;border-radius:10px;font-size:12px;font-weight:bold}.bd.s{background:#e8f8f5;color:#27ae60}.bd.d{background:#fdedec;color:#c0392b}.tn{font-size:12px;color:#7f8c8d;margin-top:10px;line-height:1.5}#c{width:100%;height:500px}'
J=json.dumps(cd,ensure_ascii=False)
H=f'''<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>搜打撤 负反馈曲线</title><script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script><style>{S}</style></head><body><h1>🎮 搜打撤 — 单局损失→负反馈 曲线</h1><div class="sub">基于 {m["n_matches"]} 局 / {m["n_players"]} 名玩家的 B 样条拟合</div><div class="l"><div class="ca"><div id="c"></div></div><div class="pa"><h3>📋 输入本局数据</h3><div class="f"><label>💰 携带总价值</label><input type="number" id="cr" value="50000" min="1" step="100"></div><div class="f"><label>💸 丢失总价值</label><input type="number" id="ls" value="35000" min="0" step="100"></div><div class="f"><label>🔥 挫败感来源</label><div class="rg"><label><input type="radio" name="fs" value="death" checked><span>💀 死亡</span></label><label><input type="radio" name="fs" value="mixed"><span>⚖️ 相当</span></label><label><input type="radio" name="fs" value="loss"><span>📉 物品损失</span></label></div></div><div class="rb"><div class="rr"><span class="l">📊 损失率</span><span class="v" id="lr">--</span></div><div class="rr"><span class="l">🔮 预挫败感</span><span class="v hl" id="pf">--</span></div><div class="rr"><span class="l">📍 位置</span><span id="po" class="bd s">计算中</span></div><div class="rr"><span class="l">📈 超越玩家</span><span class="v" id="pc">--</span></div></div><div class="tn" id="tn">⚡ 阈值拐点：{m["threshold_pct"]}%（95%CI {m["threshold_ci_low_pct"]}%~{m["threshold_ci_high_pct"]}%）</div></div></div><script>
const D={J};
function pF(r){{const s=D.spline_fit;if(r<=s[0].x)return s[0].y;if(r>=s[s.length-1].x)return s[s.length-1].y;for(let i=0;i<s.length-1;i++){{if(r>=s[i].x&&r<=s[i+1].x){{const t=(r-s[i].x)/(s[i+1].x-s[i].x);return s[i].y+t*(s[i+1].y-s[i].y)}}}}return 5}}
function dr(){{const ca=+document.getElementById('cr').value||1,lo=+document.getElementById('ls').value||0,r=Math.min(lo/ca,1),pf=pF(r),th=D.meta.threshold_pct/100,bi=D.binned,sp=D.spline_fit;Plotly.newPlot('c',[{{x:bi.map(p=>p.loss_rate_mid),y:bi.map(p=>p.frustration_mean),error_y:{{type:'data',array:bi.map(p=>p.ci),visible:true}},mode:'markers',name:'箱±95%CI',marker:{{color:'#7f8c8d',size:8}}}},{{x:sp.map(p=>p.x),y:sp.map(p=>p.y),mode:'lines',name:'B样条',line:{{color:'#c0392b',width:3}}}},{{x:[th,th],y:[0,10],mode:'lines',name:'阈值'+D.meta.threshold_pct+'%',line:{{color:'#e67e22',width:2,dash:'dash'}}}},{{x:[r],y:[pf],mode:'markers+text',name:'你',text:['←你'],textposition:'top center',textfont:{{size:13,color:'#e67e22'}},marker:{{color:'#e67e22',size:18,symbol:'star',line:{{width:2,color:'#fff'}}}}}}],{{title:'单局损失率→负反馈(挫败感1~10)',xaxis:{{title:'损失率',range:[-0.02,1.02],tickformat:'.0%',dtick:0.1}},yaxis:{{title:'挫败感',range:[0.5,10.5],dtick:1}},hovermode:'closest',legend:{{orientation:'h',y:-0.2}},margin:{{l:50,r:20,t:40,b:80}},shapes:[{{type:'rect',x0:D.meta.threshold_ci_low_pct/100,x1:D.meta.threshold_ci_high_pct/100,y0:0,y1:10,fillcolor:'rgba(230,126,34,0.08)',line:{{width:0}}}}]}},{{responsive:true,displayModeBar:false}})}}
function up(){{const ca=+document.getElementById('cr').value||1,lo=+document.getElementById('ls').value||0,r=Math.min(lo/ca,1);const s=document.querySelector('input[name="fs"]:checked').value;const adj=D.frustration_source_adjust||{{death_dominated:0.8,loss_dominated:-0.5,mixed:0}};let a=s==='death'?adj.death_dominated:s==='loss'?adj.loss_dominated:adj.mixed;let b=pF(r),f=Math.min(10,Math.max(1,b+a));document.getElementById('lr').textContent=(r*100).toFixed(1)+'%';document.getElementById('pf').textContent=f.toFixed(1)+'/10';const th=D.meta.threshold_pct/100,bg=document.getElementById('po');if(r<th*0.7){{bg.className='bd s';bg.textContent='安全'}}else if(r<th){{bg.className='bd s';bg.style.background='#fef9e7';bg.style.color='#f39c12';bg.textContent='接近拐点'}}else if(r<th*1.3){{bg.className='bd d';bg.style.background='#fdedec';bg.style.color='#e67e22';bg.textContent='拐点区间'}}else{{bg.className='bd d';bg.textContent='超越拐点'}}let below=0,tot=0;for(const b of(D.binned||[])){{tot+=b.n;if(b.loss_rate_mid<=r)below+=b.n}}document.getElementById('pc').textContent=tot>0?Math.round(below/tot*100)+'%':'--';dr()}}
up();document.querySelectorAll('#cr,#ls,input[name="fs"]').forEach(el=>el.addEventListener('input',up))
</script></body></html>'''
(ROOT/"index.html").write_text(H,encoding="utf-8")
print(f'index.html generated ({len(H)} bytes)')